### ISSUE TITLE
Bot won't respond to commands.

### ISSUE THREAD

**Issue by JoshVerboom** [BitQuote/AwesomeBot#178]
When asking Awesomebot to perform a command, he won't do it.
For example: To use the config panel i need te use the command provided for it. But when i try to execute it, nothing happens.

Please help

**Comment by NickArt1342** [comment]
I'm having the same issue. Not one single command works. It won't even show the time or my glorious afk message :(

**Comment by 4AG** [comment]
Pm messages are down

**Comment by NickArt1342** [comment]
It responds to mentions but not to commands.

**Comment by 10thTARDIS** [comment]
[System status](http://status.awesomebot.xyz/) says that the bot is currently experiencing a major outage.

**Comment by roberestarkk** [comment]
Can confirm. The PM-ing system is broken and the System Status reports 100% fine.

Both config and help are definitely non-functional, I had to pipe help to public just to figure out that config is a PM-based command.

**Comment by Chris92de** [comment]
At the moment the bot has some issues, which we apologize for. This includes:

- the bot not responding at all or taking long time to respond
- the admin panel not being available since PM commands are not working 

The bot not responding to PMs is an issue with the version of the Discord.js library we're using for the bot and we've forwarded that issue to their maintainers, who are currently looking into it for a fix.

In the meantime we're hard at work to bring you the new version 4 of AwesomeBot as soon as possible. Most of the existing issues will be fixed as well as some exciting features will come up. At the moment there is no ETA for v4 of AwesomeBot. Any Updates will be posted in #updates on our official Discord server: http://discord.awesomebot.xyz

Thank you for your understanding
